#25 Issue/25（途中）
taka-123/VeggieShop pull request #26
Opened 2020-05-12 03:23 UTC by taka-123

デフォルト：新着順でLIMIT表示

HTML等の変更はまだ

2020-05-12 12:20 UTC, primestyleus commented
@taka-123

2020-05-12 12:39 UTC, primestyleus commented
@taka-123 
以下でこちらでは動作が確認できました。そちらでも試していただけますか？

item.php
function get_limit_items($db, $is_open = false, $sort = 'created DESC', $start_array_num, $needs){
  $sql = '
    SELECT
      item_id, 
      name,
      stock,
      price,
      image,
      status
    FROM
      items
  ';
  if($is_open === true){
    $sql .= '
      WHERE status = 1
    ';
  }
  $sql .= '
    ORDER BY ?
  ';
  $sql .= '
    LIMIT ?, ?
  ';
  $params = array($sort, $start_array_num, $needs);

  return fetch_all_query($db, $sql, $params);
}

html/index.php
$sort = 'created DESC';
$items = get_limit_items($db, true, $sort, $start_array_num, INDEX_NUM_MAX);

2020-05-12 12:57 UTC, taka-123 commented
@primestyleus 
ありがとうございます。
'ORDER BY ?'でもできるんですね。
できないのかと思い、'?'として、ORDER BYから全てを変数に入れる形でコードを書いてしまいました。
また修正するとして、再度pushしてみても良いですか？

2020-05-12 13:47 UTC, primestyleus commented
@taka-123 
はい、修正したらぜひPUSHしてください！

2020-05-12 14:05 UTC, taka-123 commented
@primestyleus 
なぜか
$sql .= $sort_sql;
とすると上手くいき、

$sql .= 'ORDER BY ?';
$param = array($sort_sql, 〜)
とすると、ソートが効かず登録順（昇順）＝古い順になります。

とりあえずこれで要件自体は満たしていると思うのですが。

2020-05-12 14:25 UTC, primestyleus requested changes
sortsテーブルが追加となっていると思います。そちらの作成SQLも一緒にコミットしていただけますか？
※sortsは固定データだと思いますので、テーブルではなくてconst.phpなどに定義する形でもいいと思います。

2020-05-13 11:42 UTC, primestyleus approved these changes
@taka-123 
OKです。マージしますね！

2020-05-13 11:43 UTC, merged