#27 人気ランキングを作成しました
taka-123/VeggieShop pull request #28
Opened 2020-05-13 13:42 UTC by taka-123

2020-05-13 14:00 UTC, primestyleus requested changes
SQLでのカウント方法など、うまくできていると思います！

2020-05-13 14:00 UTC, primestyleus commented on www/html/index.php
> +$popular_item_3 = get_popular_items($db, 3);
（TOP5にあとで仕様がかわったらと考えてみるといいと思いますが、）
マジックナンバーは使わないようにしましょう。変数名にも数字は使わないほうがいいです。

2020-05-13 14:11 UTC, taka-123 commented on www/html/index.php
> +$popular_item_3 = get_popular_items($db, 3);
@primestyleus 
ありがとうございます。
変数名に数字を使わない件、了解致しました。

TOP5等に使用が変わった場合を考えて、関数の汎用性を高められるかと思いLIMITの値を?にしてみたのですが、そこも直した方が良いですか？

2020-05-14 03:36 UTC, taka-123 commented on www/html/index.php
> +$popular_item_3 = get_popular_items($db, 3);
@primestyleus 
修正してみました。お手隙の際にご確認お願い致します。

2020-05-14 03:37 UTC, primestyleus approved these changes
OKです！マージします。

2020-05-14 03:37 UTC, primestyleus commented on www/html/index.php
> +$popular_item_3 = get_popular_items($db, 3);
@taka-123 
LIMITに?を使ってバインディングするのはそのままでいいと思います！

2020-05-14 03:37 UTC, merged