#29 ページングの際、ソート情報を引継ぎ & プルダウンのソート情報を固定表示
taka-123/VeggieShop pull request #30
Opened 2020-05-14 14:42 UTC by taka-123

2020-05-14 14:51 UTC, primestyleus requested changes
いい感じですね！一点だけもう少し最適化できる部分があるので、変更をリクエストさせていただきます。

2020-05-14 14:51 UTC, primestyleus commented on www/view/index_view.php
> +          <?php if($sort_key === $sort['sort_key']) { ?>
@taka-123 
動作としては問題ないと思いますが、もう少しきれいにすることができます。
`<?php if ($sort_key === $sort['sort_key']){ print 'selected' }?>`
のようにselctedの出し分けだけを分岐させるといいかと思います！

2020-05-15 14:01 UTC, taka-123 commented on www/view/index_view.php
> +          <?php if($sort_key === $sort['sort_key']) { ?>
@primestyleus 
お返事遅くなってしまいすみません。
内容は確認していたのですが。

条件分岐確かにそのようにすると綺麗ですね！全然思いつきませんでした。
ありがとうございます。

2020-05-15 14:35 UTC, primestyleus approved these changes

2020-05-15 14:35 UTC, merged